<a href="https://colab.research.google.com/github/jmoralespineda/machine-learning/blob/main/Ej_dem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$ Cov(X,Y) = E[XY^T] − E[X]⋅E[Y]

In [1]:
import numpy as np

# Definición de los vectores aleatorios X y Y
X = np.array([1, 2, 3])  # Por ejemplo
Y = np.array([4, 5, 6])  # Por ejemplo

# Cálculo de la media de X y Y
mu_X = np.mean(X)
mu_Y = np.mean(Y)

# Cálculo de E[XY^T]
EXY_T = np.outer(X, Y)

# Covarianza entre X e Y
Cov_XY = EXY_T - np.outer(X, mu_Y) - np.outer(mu_X, Y) + mu_X * mu_Y

# Cálculo de E[X] * E[Y]
EX_EY = mu_X * mu_Y

# Mostrar los resultados
print("Covarianza (Cov(X,Y)):\n", Cov_XY)
print("E[X] * E[Y]:", EX_EY)

Covarianza (Cov(X,Y)):
 [[ 1.  0. -1.]
 [ 0.  0.  0.]
 [-1.  0.  1.]]
E[X] * E[Y]: 10.0


Cov(X,Y)=E[(X−μX)(Y−μY)]=E[XY]−E[X]⋅E[Y].

In [5]:
import numpy as np

# Definición de los vectores aleatorios X y Y
X = np.array([1, 2, 3])  # Por ejemplo
Y = np.array([4, 5, 6])  # Por ejemplo

# Cálculo de la media de X y Y
mu_X = np.mean(X)
mu_Y = np.mean(Y)

# Cálculo de E[(X - mu_X)(Y - mu_Y)]
EXY = np.mean((X - mu_X) * (Y - mu_Y))

# Cálculo de E[XY]
EXY_2 = np.mean(X * Y)

# Cálculo de E[X] * E[Y]
EX_EY = mu_X * mu_Y

# Mostrar los resultados
print("Covarianza (Cov(X,Y)):", EXY)
print("E[XY]:", EXY_2)
print("E[X] * E[Y]:", EX_EY)

Covarianza (Cov(X,Y)): 0.6666666666666666
E[XY]: 10.666666666666666
E[X] * E[Y]: 10.0


$ Cov(X,Y) = E[(X−μ X)^2 = E[X^2] - E^2[X]

In [6]:
import numpy as np

# Definición de los datos
X = np.array([1, 2, 3, 4, 5])  # Por ejemplo

# Cálculo de la media de X
mu_X = np.mean(X)

# Cálculo de E[(X - mu_X)^2]
EX_minus_mu_X_sq = np.mean((X - mu_X)**2)

# Cálculo de E[X^2]
EX_sq = np.mean(X**2)

# Cálculo de (E[X])^2
EX_sq_mean = np.mean(X)**2

# Mostrar los resultados
print("Covarianza (E[(X - mu_X)^2]):", EX_minus_mu_X_sq)
print("E[X^2]:", EX_sq)
print("(E[X])^2:", EX_sq_mean)

Covarianza (E[(X - mu_X)^2]): 2.0
E[X^2]: 11.0
(E[X])^2: 9.0
